---
title: "Invasibility"
author: "Lucas A. Nell"
date: "`r Sys.setenv(TZ='America/Chicago'); format(Sys.Date(), '%d %b %Y')`"
output:
  github_document:
    toc: true
    toc_depth: 2
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width = 6.5, fig.height = 4.5, dev = "svglite")
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 8L)
```

```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
```

```{r load-libs}
suppressPackageStartupMessages({
    library(tidyverse)
    library(sauron)
})
# theme_set(theme_black())
```


## Required functions

```{r req_fxns}

# fitness <- function(V_resident, V_invader, N_resident, N_invader, eta, d, 

fitness <- function(V_invader, Omega, eta, d, 
                    f = 0.1, a0 = 0.5, r0 = 0.5) {
    C <- matrix(eta, 2, 2)
    diag(C) <- 1
    Vi <- as.matrix(V_invader)
    # one_resident <- function(j) {
    #     Vj <- V_resident[j,,drop=FALSE]
    #     N_resident[j] * as.numeric(exp(- d * Vj %*% t(Vj)))
    # }
    # Omega <- Ni + sum(sapply(1:nrow(V_resident), one_resident))
    exp(r0 - f * Vi %*% C %*% t(Vi) - a0 * exp(- Vi %*% t(Vi)) * Omega)
}
# Omega at stable points
Omega_hat <- function(eta, f = 0.1, a0 = 0.5, r0 = 0.5) {
    rho <- ifelse(eta < 0, f * (1 + eta), f * (1 - eta))
    (rho / a0) * exp((r0 / rho) - 1)
}


fitness_landscape <- function(d_, eta_, max_mag = 6) {

    O <- Omega_hat(eta_)
    pts <- as.matrix(stable_points(eta_)[1,])

    hm_df <- crossing(V1 = seq(-max_mag, max_mag, length.out = 100),
                      V2 = seq(-max_mag, max_mag, length.out = 100)) %>% 
        mutate(fit = pmap_dbl(list(V1, V2),
                              ~ fitness(V_invader = cbind(..1, ..2), 
                                        Omega = O,
                                        eta = eta_, d = d_)))

    hm_df %>% 
        mutate(invasible = factor(ifelse(fit >= 1, 1, 0),
                                  levels = 0:1,
                                  labels = c("no", "yes"))) %>% 
        ggplot() +
        geom_raster(aes(V1, V2, fill = fit), interpolate = FALSE) +
        # geom_raster(aes(V1, V2, fill = invasible), interpolate = FALSE) +
        stable_points(eta_, return_geom = TRUE) +
        unstable_points(eta_, return_geom = TRUE) +
        # facet_wrap(~ Ni, nrow = 2, labeller = label_parsed) +
        scale_fill_gradient2("F", high = "firebrick", low = "dodgerblue3",
                             mid = "white", midpoint = 1) +
        # scale_fill_manual(values = c("white", "gray60")) +
      xlab("Trait 1") +
      ylab("Trait 2") +
      coord_equal()
}

```


```{r make_plots}
plots <- map(c(-0.6, 0, 0.6), fitness_landscape)
# for (i in 1:length(plots)) {
#   ggsave(sprintf("~/Desktop/landscape%i.pdf", i), plots[[i]], width = 6.5, height = 4.5)
# }
```


### When eta < 0

```{r neg_eta_plot, echo = FALSE}
plots[[1]]
```


### When eta == 0
```{r zero_eta_plot, echo = FALSE}
plots[[2]]
```


### When eta > 0

```{r pos_eta_plot, echo = FALSE}
plots[[3]]
```



```{r}


eta = 0.6
d = 1
V_invader = stable_points(eta)[1,] * 0.9
V_resident = stable_points(eta)[,1]

f = 0.1
a0 = 0.5
r0 = 0.5

Omega <- Omega_hat(eta)

C <- matrix(eta, 2, 2)
diag(C) <- 1
Vi <- as.matrix(V_invader)
rho <- 1 - abs(eta)

exp(r0 - f * {Vi[1]^2 + 2 * eta * Vi[1] * Vi[2] + Vi[2]^2 - rho * exp(r0 / (f * rho) - Vi[1]^2 - Vi[2]^2)})

exp(r0 - a0 * Omega * exp(- Vi %*% t(Vi)) - f * Vi %*% C %*% t(Vi)) %*% 
  (2 * a0 * Omega * exp(- Vi %*% t(Vi)) %*% Vi - f * Vi %*% (C + t(C)))


exp(r0 - a0 * Omega * exp(- Vi %*% t(Vi)) - f * Vi %*% C %*% t(Vi)) %*% 
  (2 * (a0 * Omega * exp(- Vi %*% t(Vi)) %*% Vi - f * Vi %*% C))


```

