---
title: "Alternative stable states simulations"
author: "Lucas A. Nell"
date: "10/25/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Alternative stable states simulations}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 8L)
```
```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
suppressPackageStartupMessages({
    library(tidyverse)
    library(evoASS)
})
```


```{r adaptive_dynamics}

sim_output <- adaptive_dynamics(
        V0 = rep(1, 2),
        N0 = 1,
        f = 0.1,  # cost of the trait on the growth rate
        g = 0.1,  # benefit of the trait on density dependence
        eta = 0.1, #0.2,  # the non-additive effects of traits on `r`
        r0 = 1 * 0.5,  # baseline growth rate
        d = -0.1 * 0.25,  # changes how the focal line is affected by other lines' trait values
        max_t = 1e4,
        min_N = 1e-4,
        mut_sd = 0.1,
        mut_prob = 0.01,
        show_progress = TRUE,
        max_clones = 1e4)




V <- do.call(rbind, sim_output$V)

sapply(sim_output$N, length) %>% plot(type = "l")


NVt <- 
    data_frame(time = 1:length(sim_output$N) %>% 
                   lapply(function(i) rep(i, length(sim_output$N[[i]]))) %>% 
                   c(recursive = TRUE),
               clone = c(sim_output$I, recursive = TRUE),
               N = c(sim_output$N, recursive = TRUE)) %>% 
    mutate(V1 = sapply(clone, function(i) sim_output$V[[i+1]][1]),
           V2 = sapply(clone, function(i) sim_output$V[[i+1]][2])) %>% 
    gather("trait", "value", V1:V2, factor_key = TRUE)
N_byt <- NVt %>% 
        group_by(time) %>% 
        summarize(N = sum(N)) %>% 
        ungroup()

NVt %>% 
    ggplot(aes(time, value)) +
    geom_point(shape = 1, alpha = 0.5) +
    facet_wrap(~ trait) +
    theme_classic()

N_byt %>% 
    ggplot(aes(time, N)) +
    geom_line() +
    theme_classic()



```


```{r R_version, eval = FALSE, echo = FALSE}

library(progress)


make_env <- function() {
    sim_env <- new.env()
    with(sim_env, {
        n_clones <- 1
        V <- matrix(rep(c(1, 1), n_clones), ncol = 2)
        N <- matrix(1, 1, nrow(V))
        f <- 0.1 * 0.1
        g <- 0.1
        eta <- 0.1 * 2
        C <- matrix(c(1, rep(eta, 2), 1), 2, 2)
        r0 <- 1
        d <- -0.01
        maxt <- 1e4
        
        min_N <- 1e-4
        mut_sd <- 0.1 * 2
        mut_prob <- 0.01
        
        # traits and abundances through time:
        Vt <- rep(list(matrix(NA_real_, 0, 2)), maxt + 1)
        Nt <- rep(list(matrix(NA_real_, 1, 0)), maxt + 1)
        Vt[[1]] <- V
        Nt[[1]] <- N
    })
    
    return(sim_env)
}

do_sim <- function(sim_env) {
    
    with(sim_env, {
        
        pb <- progress_bar$new(total = maxt,
                               format = "[:bar] :percent in :elapsed",
                               clear = FALSE)
        
        for (t in 1:maxt) {
            
            N <- N * F_t(V, N, f, g, C, r0, d)
            # See if any go extinct:
            extant <- as.logical(N >= min_N)
            if (sum(extant) == 0) break;
            N <- N[,extant,drop=FALSE]
            V <- V[extant,,drop=FALSE]
            # Seeing if I should add new clones:
            muts <- runif(length(N)) < mut_prob
            if (any(muts)) {
                N[,muts] <- N[,muts] - 1.01 * min_N
                n_muts <- sum(muts)
                new_N <- matrix(1.01 * min_N, 1, n_muts)
                new_V <- lapply(which(muts),
                                function(i) {
                                    cbind(evoASS:::trunc_rnorm_(mu = V[i,1], sigma = mut_sd),
                                          evoASS:::trunc_rnorm_(mu = V[i,2], sigma = mut_sd))
                                })
                new_V <- do.call(rbind, new_V)
                N <- cbind(N, new_N)
                V <- rbind(V, new_V)
            }
            Nt[[t+1]] <- N
            Vt[[t+1]] <- V
            pb$tick()
        }
    })
    
    invisible(sim_env)
}

sim_env <- make_env()
do_sim(sim_env)

with(sim_env, {

    NVt <- lapply(1:length(Vt),
                  function(i) {
                      nn <- Nt[[i]]
                      vv <- Vt[[i]]
                      return(cbind(i, t(nn), vv))
                  }) %>%
        do.call(what = rbind) %>%
        as_data_frame() %>%
        set_names(c("time", "N", "V1", "V2")) %>%
        mutate(time = as.integer(time)) %>%
        group_by(time) %>%
        mutate(clone = 1:n()) %>%
        ungroup() %>%
        gather("trait", "value", V1:V2, factor_key = TRUE)

    N_byt <- sim_env$NVt %>%
        group_by(time) %>%
        summarize(N = sum(N)) %>%
        ungroup()
})


sim_env$NVt %>%
    ggplot(aes(time, value)) +
    geom_point(shape = 1, alpha = 0.5) +
    facet_wrap(~ trait) +
    theme_classic()

sim_env$N_byt %>%
    ggplot(aes(time, N)) +
    geom_line() +
    theme_classic()

```

