---
title: "Alternative stable states model"
author: "Lucas A. Nell"
date: "10/21/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Alternative stable states model}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 8L)
```


## Note on notation

Below, $*$ is vector multiplication
and
${}^T$ represents transpose.


## Model


Fitness for clone $i$ ($i \in \{1, \ldots, n\}$) at time $t$ ($F_{it}$) is as follows:

$$
\begin{align}
    F_{i} &= \exp \left\{ r(V_i) - \alpha_{ii}(V_i) N_i - \sum_{j \ne i}^{n}{
        \alpha_{ij}(V_i, V_j) N_j}  \right\}\\
    r(V_i) &= r_0 - f ~ V_i * C * V_i^T \\
    \alpha_{ii}(V_i) &= g ~\exp \left\{- V_i * V_i^T \right\} \\
    \alpha_{ij}(V_i, V_j) &= g ~\exp \left\{- V_i * V_i^T - d ~ V_j * V_j^T \right\} \\
    C &=
        \begin{pmatrix}
            1       & \eta  \\
            \eta    & 1     \\
        \end{pmatrix} \\
\end{align}
$$

where
$V$ is an $n \times q$ matrix of trait values for all $n$ clones,
$V_i$ is a $1 \times q$ vector referring to the $i$th row in $V$,
$N$ is a $1 \times n$ vector of population abundances for all lines,
$r_0$ is the baseline growth rate,
$f$ is the cost of the trait on the growth rate,
$g$ is the benefit of the trait on density dependence,
$d$ changes how the focal line is affected by other lines' trait values,
and
$\eta$ is the non-additive effects of traits on $r$.



# Adaptive dynamics

From Tobin and Tony's paper:

> The model is initiated with single resource and consumer clones, and with 
> probability 0.01 each iteration, a clone gives rise to a daughter clone by
> selecting trait values from normal distributions with means given by the
> mother's trait values and standard deviation $\sigma$. The density of each clone is
> given by equations (1) or (2), and clones that drop below a density of 0.0001
> are assumed to go extinct.

I did the same thing but started with one competitor and used the equations above
for densities.



# Quantitative genetics

Writing out the fitness function entirely:

$$
\begin{align}
\begin{split}
F_{i} = \exp \{ 
    & ~ r_0 - f ~ V_i * C * V_i^T - g ~ N_i ~\text{e}^{- V_i * V_i^T } - \\
    & ~ \sum_{j \ne i}^{n}{ g ~ N_j ~\text{e}^{- V_i * V_i^T - d ~ V_j * V_j^T } } \}
\end{split}
\end{align}
$$

Simplifying a bit:

$$
\begin{align}
F_{i} = \exp \left\{ 
        r_0 - f ~ V_i * C * V_i^T - g ~\text{e}^{ - V_i * V_i^T } 
        \left( ~ N_i + \sum_{j \ne i}^{n}{ N_j ~ \text{e}^{ - d ~ V_j * V_j^T } } ~ \right)
    \right\}
\end{align}
$$

Now I can calculate the partial derivative $\frac{\partial F_i}{\partial V_i}$:

$$
\begin{align}
\begin{split}
\frac{\partial F_i}{\partial V_i} = \exp & \left\{
        r_0 - f ~ V_i * C * V_i^T - g ~\text{e}^{ - V_i * V_i^T } 
        \left( ~ N_i + \sum_{j \ne i}^{n}{ N_j ~ \text{e}^{ - d ~ V_j * V_j^T } } ~ \right)
    \right\} \cdot \\
    & \quad \left[ 
        -f ~ V_i * (C + C^T) + 2 ~ g ~ V_i ~ \text{e}^{-V_i * V_i^T} 
        \left(
            N_i + \sum_{j \ne i}^{n}{N_j ~ \text{e}^{-d ~ V_j * V_j^T} }
        \right)
    \right]
\end{split}
\end{align}
$$


Then trait values changed for species $i$ as follows:

$$
V_i &= V_i + \left( \frac{1}{F_i} \frac{\partial F_i}{\partial V_i} \right) \sigma^2_i
$$

where $\sigma^2_i$ is the additive genetic variance.

This expands and simplifies to the following:

$$
\begin{align}
V_i &= V_i +  \sigma^2_i \cdot
    \left[ 
        -f ~ V_i * (C + C^T) + 2 ~ g ~ V_i ~ \text{e}^{-V_i * V_i^T} 
        \left(
            N_i + \sum_{j \ne i}^{n}{N_j ~ \text{e}^{-d ~ V_j * V_j^T} }
        \right)
    \right]
\end{align}
$$

