---
title: "Quantitative genetics simulations"
author: "Lucas A. Nell"
date: "10/25/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Quantitative genetics simulations}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE,
  eval = TRUE
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 8L)
```
```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
suppressPackageStartupMessages({
    library(tidyverse)
    library(sauron)
})
```



## Doing and saving simulations



### Two traits

```{r, run_sims_q2, eval = FALSE, echo = TRUE}
set.seed(2028111205)
seeds <- sample.int(.Machine$integer.max, 9)  # <- so individual runs can be re-evaluated
q <- 2
i <- 1
for (e in -1:1) {
    for (d in -1:1) {
        args <- quant_gen_args(e, d, q)
        cat(sprintf("\n\neta: %.2g || d: %.2g (%i / 9) \n", args$eta, args$d, i))
        set.seed(seeds[i])
        qg <- do.call(quant_gen, args)
        fn <- sprintf("results/quant_gen/q%i/eta=%s__d=%s.rds", q, e, d)
        saveRDS(qg, fn, compress = FALSE)
        i <- i + 1
    }
}
```


### Three traits

```{r, run_sims_q3, eval = FALSE, echo = TRUE}
# Takes ~3.5 hrs
set.seed(1713696743)
seeds <- sample.int(.Machine$integer.max, 9)  # <- so individual runs can be re-evaluated
q <- 3
i <- 1
for (e in -1:1) {
    for (d in -1:1) {
        args <- quant_gen_args(e, d, q)
        cat(sprintf("\n\neta: %.2g || d: %.2g (%i / 9) \n", args$eta, args$d, i))
        set.seed(seeds[i])
        qg <- do.call(quant_gen, args)
        fn <- sprintf("results/quant_gen/q%i/eta=%s__d=%s.rds", q, e, d)
        saveRDS(qg, fn, compress = FALSE)
        i <- i + 1
    }
}
```




## Unstable state at V = 0

Below shows that when all lineages' traits are at zero, this is an unstable state:
They don't move from it without perturbation, but its primary eigenvalue is quite high
($\gg 1$).


```{r unstable_zeros2}
unqs <- as.list(rep(NA, 9))
eigens <- numeric(9)
q <- 2
n <- 100
args <- list(
    V = eval(formals(quant_gen)$V0),
    N = eval(formals(quant_gen)$N0),
    f = formals(quant_gen)$f,
    g = formals(quant_gen)$g,
    C = matrix(1, q, q),
    r0 = formals(quant_gen)$r0,
    d = 0,
    add_var = eval(formals(quant_gen)$add_var)
)
i <- 1
for (e in -1:1) {
    for (d in -1:1) {
        args_qg <- quant_gen_args(e, d, q)
        args$d <- args_qg$d
        args$C[lower.tri(args$C)] <- args_qg$eta
        args$C[upper.tri(args$C)] <- args_qg$eta
        changes <- do.call(sauron:::sel_str_cpp, 
                           args[names(args)[names(args) != "add_var"]])
        jc_mat <- do.call(sauron:::jacobian_cpp, 
                           args[names(args)[names(args) != "r0"]])
        unqs[[i]] <- unique(changes)
        eigens[i] <- Re(eigen(jc_mat, only.values = TRUE, symmetric = FALSE)$values[1])
        i <- i+1
    }
}
sapply(unqs, nrow)
do.call(rbind, unqs)
range(eigens)
```


```{r unstable_zeros3}
unqs <- as.list(rep(NA, 9))
eigens <- numeric(9)
q <- 3
n <- 100
args <- list(
    V = eval(formals(quant_gen)$V0),
    N = eval(formals(quant_gen)$N0),
    f = formals(quant_gen)$f,
    g = formals(quant_gen)$g,
    C = matrix(1, q, q),
    r0 = formals(quant_gen)$r0,
    d = 0,
    add_var = eval(formals(quant_gen)$add_var)
)
i <- 1
for (e in -1:1) {
    for (d in -1:1) {
        args_qg <- quant_gen_args(e, d, q)
        args$d <- args_qg$d
        args$C[lower.tri(args$C)] <- args_qg$eta
        args$C[upper.tri(args$C)] <- args_qg$eta
        changes <- do.call(sauron:::sel_str_cpp, 
                           args[names(args)[names(args) != "add_var"]])
        jc_mat <- do.call(sauron:::jacobian_cpp, 
                           args[names(args)[names(args) != "r0"]])
        unqs[[i]] <- unique(changes)
        eigens[i] <- Re(eigen(jc_mat, only.values = TRUE, symmetric = FALSE)$values[1])
        i <- i+1
    }
}
sapply(unqs, nrow)
do.call(rbind, unqs)
range(eigens)
```
