---
title: "Simulations"
author: "Lucas A. Nell"
date: "10/25/2018"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simulations}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  dev = "svglite", 
  fig.width = 6,
  fig.height = 4,
  echo = FALSE,
  eval = TRUE
)
knitr::opts_knit$set(root.dir = normalizePath(".."))
options(tibble.print_min = 4L, tibble.print_max = 8L)
```
```{r source_Rprofile, echo = FALSE}
if (!isTRUE(getOption('knitr.in.progress'))) source(".Rprofile")
suppressPackageStartupMessages({
    library(tidyverse)
    library(sauron)
})
```



## Doing and saving simulations

```{r do_sims, echo = TRUE}
# Create list for running a set of simulations:
quant_gen_pars <- function(eta_sign, d_sign, q, n = 100) {
    # Other parameter values that I'll keep constant:
    args <- list(
        n_reps = 100,
        V0 = rep(list(matrix(0, 1, q)), n),
        N0 = rep(1, n),
        f = 0.1,  # cost of the trait on the growth rate
        g = 0.5,  # benefit of the trait on density dependence
        r0 = 0.5,
        add_var = rep(0.5, n),
        mut_sd = 1,
        keep_pos = FALSE,
        start_t = 0,
        max_t = 1e6,
        min_N = 1e-4,
        save_every = 1000,
        show_progress = TRUE,
        n_cores = 4)
    # the non-additive effects of traits on `r`:
    if (grepl("^p", eta_sign, TRUE)) {
        args$eta <- 0.01
    } else if (grepl("^z", eta_sign, TRUE)) {
        args$eta <- 0
    } else {
        args$eta <- -0.01
    }
    # changes how the focal line is affected by other lines' trait values:
    if (grepl("^p", d_sign, TRUE)) {
        args$d <- 1e-4
    } else if (grepl("^z", d_sign, TRUE)) {
        args$d <- 0
    } else {
        args$d <- -0.1
    }

    return(args)
}
```


### Two traits


```{r, run_sims_q2, eval = FALSE, echo = TRUE}
# Takes ~ 2.1 hrs
set.seed(2028111205)
seeds <- sample.int(.Machine$integer.max, 9)  # <- so individual runs can be re-evaluated
i <- 1
for (e in c("n", "z", "p")) {
    for (d in c("n", "z", "p")) {
        cat(sprintf("\n\neta: %s || d: %s (%i / 9) \n", e, d, i))
        set.seed(seeds[i])
        args <- quant_gen_pars(e, d, q = 2)
        qg <- do.call(quant_gen, args)
        saveRDS(qg, sprintf("results/q2/%s-eta_%s-d.rds", e, d), compress = FALSE)
        i <- i + 1
    }
}
```


### Three traits

```{r, run_sims_q3, eval = FALSE, echo = TRUE}
# Takes ~3.5 hrs
set.seed(1713696743)
seeds <- sample.int(.Machine$integer.max, 9)  # <- so individual runs can be re-evaluated
i <- 1
for (e in c("n", "z", "p")) {
    for (d in c("n", "z", "p")) {
        cat(sprintf("\n\neta: %s || d: %s (%i / 9) \n", e, d, i))
        set.seed(seeds[i])
        args <- quant_gen_pars(e, d, q = 3)
        qg <- do.call(quant_gen, args)
        saveRDS(qg, sprintf("results/q3/%s-eta_%s-d.rds", e, d), compress = FALSE)
        i <- i + 1
    }
}
```
