# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Adaptive dynamics.
#'
#'
#' @noRd
#'
adaptive_dynamics_cpp <- function(V0, N0, f, g, eta, r0, d, max_t, min_N, mut_sd, mut_prob, show_progress, max_clones, save_every) {
    .Call(`_evoASS_adaptive_dynamics_cpp`, V0, N0, f, g, eta, r0, d, max_t, min_N, mut_sd, mut_prob, show_progress, max_clones, save_every)
}

#' One round of quantitative genetics.
#'
#' Higher-up function(s) should create `C` from `eta` and should handle any outputs.
#'
#'
#' @noRd
#'
NULL

#' Version of above for use in R for testing.
#'
#' @noRd
#'
dF_dVi_cpp <- function(V_i, V_nei, N_i, N_nei, f, g, C, r0, d) {
    .Call(`_evoASS_dF_dVi_cpp`, V_i, V_nei, N_i, N_nei, f, g, C, r0, d)
}

#' Normal distribution truncated above zero.
#'
#' From `http://web.michaelchughes.com/research/sampling-from-truncated-normal`
#'
#' @noRd
#'
trunc_rnorm_cpp <- function(N, mu, sigma) {
    .Call(`_evoASS_trunc_rnorm_cpp`, N, mu, sigma)
}

#' Fitness at time t.
#'
#' @param V List of row vectors, each containing trait values at time t (1x2 vector)
#'     for a particular clone.
#' @param N Row vector of population abundances at time t.
#' @param f Effect of traits on growth rate.
#' @param g Effect of traits on density dependence.
#' @param C Matrix containing non-additive effects of traits on growth rate.
#' @param r0 Starting growth rate.
#' @param d Changes how the focal line is affected by other lines' trait values.
#'     If `d < 0`, then increases in `V_j` (trait that reduces competition
#'     experienced by clone `j`) increases competition experienced by clone `i`,
#'     thereby giving conflicting coevolution.
#'     Conversely, if `d > 0`, then increases in `V_j` decrease competition
#'     experienced by clone `i`, leading to nonconflicting coevolution.
#'
#'
#' @export
#'
F_t_cpp <- function(V, N, f, g, C, r0, d) {
    .Call(`_evoASS_F_t_cpp`, V, N, f, g, C, r0, d)
}

#' Same as above, but for only one clone.
#'
#' This is used for computing partial derivatives.
#'
#' @param V_i Row vector of traits for focal clone.
#' @param V_nei List of row vectors of traits for non-focal clones.
#' @param N_i Abundance for focal clone.
#' @param N_nei Row vector of abundances for non-focal clones.
#' @inheritParams F_t_cpp
#'
#' @noRd
#'
F_t_deriv_cpp <- function(V_i, V_nei, N_i, N_nei, f, g, C, r0, d) {
    .Call(`_evoASS_F_t_deriv_cpp`, V_i, V_nei, N_i, N_nei, f, g, C, r0, d)
}

